import 'package:anm_app/all_over_again/models/all_controller_binding.dart';
import 'package:anm_app/all_over_again/routes/app_pages.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

void main() async {
  await GetStorage.init();

  runApp(
    MyApp(),
    // GetMaterialApp(
    //   title: "Matrimonial App",
    //   initialRoute: AppPages.initial,
    //   getPages: AppPages.routes,
    //   theme: ThemeData(primarySwatch: Colors.red),
    //   debugShowCheckedModeBanner: false,
    // ),
  );
}

// void main() {
//   // runApp(ChangeNotifierProvider(create: ((context) => AuthAPI()), child: MyApp()));
// }

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // final value = context.watch<AuthAPI>().status;
    // print('TOP CHANGE Value changed to: $value!');
    // return MaterialApp(
    //   title: 'Flutter Demo',
    //   theme: ThemeData(
    //     fontFamily: "Metropolis",
    //     primarySwatch: Colors.red,
    //     elevatedButtonTheme: ElevatedButtonThemeData(
    //       style: ButtonStyle(
    //         backgroundColor: MaterialStateProperty.all(
    //           AppColor.orange,
    //         ),
    //         shape: MaterialStateProperty.all(
    //           StadiumBorder(),
    //         ),
    //         elevation: MaterialStateProperty.all(0),
    //       ),
    //     ),
    //     textButtonTheme: TextButtonThemeData(
    //       style: ButtonStyle(
    //         foregroundColor: MaterialStateProperty.all(
    //           AppColor.orange,
    //         ),
    //       ),
    //     ),
    //     textTheme: const TextTheme(
    //       headline3: TextStyle(
    //         color: AppColor.primary,
    //         fontSize: 16,
    //         fontWeight: FontWeight.bold,
    //       ),
    //       headline4: TextStyle(
    //         color: AppColor.secondary,
    //         fontWeight: FontWeight.bold,
    //         fontSize: 20,
    //       ),
    //       headline5: TextStyle(
    //         color: AppColor.primary,
    //         fontWeight: FontWeight.normal,
    //         fontSize: 25,
    //       ),
    //       headline6: TextStyle(
    //         color: AppColor.primary,
    //         fontSize: 25,
    //       ),
    //       bodyText2: TextStyle(
    //         color: AppColor.secondary,
    //       ),
    //     ),
    //   ),

    return GetMaterialApp(
      // title: "Matrimonial App",
      initialRoute: Routes.login,
      // initialBinding: RegisterPageBinding(),
      initialBinding: AllControllerBinding(),
      getPages: AppPages.routes,
      theme: ThemeData(primarySwatch: Colors.red),
      debugShowCheckedModeBanner: false,
    );

    // home: SplashScreenView(),
    // routes: {
    //   LandingScreen.routeName: (context) => LandingScreen(),
    //   LoginScreen.routeName: (context) => LoginScreen(),
    //   SignUpScreen.routeName: (context) => SignUpScreen(),
    //   ForgetPwScreen.routeName: (context) => ForgetPwScreen(),
    //   SendOTPScreen.routeName: (context) => SendOTPScreen(),
    //   NewPwScreen.routeName: (context) => NewPwScreen(),
    //   HomeScreen.routeName: (context) => HomeScreen(),
    //   ProfileScreen.routeName: (context) => ProfileScreen(),
    //   MoreScreen.routeName: (context) => MoreScreen(),
    //   InboxScreen.routeName: (context) => InboxScreen(),
    //   ProfileTypeScreen.routeName: (context) => ProfileTypeScreen(),
    //   AboutMeScreen.routeName: (context) => AboutMeScreen(profile_type: ""),
    //   AccountPage.routeName: (context) => AccountPage(),
    //   MessagesPage.routeName: (context) => MessagesPage(),
    //   RegisterPageView.routeName: (context) => RegisterPageView(),
    // LoginPageView.routeName: (context) => LoginPageView(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //       education: '',
    //       college: '',
    //       other_college: '',
    //       occupation: '',
    //       annual_income: '',
    //       maritial_status: '',
    //       no_of_children: '',
    //       mother_tongue: '',
    //       denomination: '',
    //       sub_castle: '',
    //       father_status: '',
    //       mother_status: '',
    //       no_of_brothers: '',
    //       no_of_sisters: '',
    //       religious_value: '',
    //       family_income: '',
    //       family_type: '',
    //       family_values: '',
    //       diet: '',
    //       drink: '',
    //       hobbies: '',
    //       languages_known: '',
    //       smoke: '',
    //       about_me_fav_thing: '',
    //     ),
    // TabsPageView.routeName: (context) => TabsPageView(),
    // CircularProgress.routeName: (context) => CircularProgress(),
    // PersonalDetailsScreen.routeName: (context) => PersonalDetailsScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //     ),
    // CurrentLocationScreen.routeName: (context) => CurrentLocationScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //     ),
    // PastorDetailsScreen.routeName: (context) => PastorDetailsScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //     ),
    // CareerDetailsScreen.routeName: (context) => CareerDetailsScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //     ),
    // SocialDetailsScreen.routeName: (context) => SocialDetailsScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //       education: '',
    //       college: '',
    //       other_college: '',
    //       occupation: '',
    //       annual_income: '',
    //     ),
    // FamilyDetailsScreen.routeName: (context) => FamilyDetailsScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //       education: '',
    //       college: '',
    //       other_college: '',
    //       occupation: '',
    //       annual_income: '',
    //       maritial_status: '',
    //       no_of_children: '',
    //       mother_tongue: '',
    //       denomination: '',
    //       sub_castle: '',
    //     ),
    // LifeStyleScreen.routeName: (context) => LifeStyleScreen(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //       education: '',
    //       college: '',
    //       other_college: '',
    //       occupation: '',
    //       annual_income: '',
    //       maritial_status: '',
    //       no_of_children: '',
    //       mother_tongue: '',
    //       denomination: '',
    //       sub_castle: '',
    //       father_status: '',
    //       mother_status: '',
    //       no_of_brothers: '',
    //       no_of_sisters: '',
    //       religious_value: '',
    //       family_income: '',
    //       family_type: '',
    //       family_values: '',
    //     ),
    // AboutMeFavThing.routeName: (context) => AboutMeFavThing(
    //       profile_type: '',
    //       salutation: '',
    //       first_name: '',
    //       middle_name: '',
    //       last_name: '',
    //       gender: '',
    //       phone_number: '',
    //       email: '',
    //       age: '',
    //       birth_place: '',
    //       height: '',
    //       weight: '',
    //       body_type: '',
    //       skin_tone: '',
    //       any_disability: '',
    //       blood_group: '',
    //       address: '',
    //       building: '',
    //       city: '',
    //       country: '',
    //       state: '',
    //       zip_code: '',
    //       pastor_name: '',
    //       church_name: '',
    //       city_name: '',
    //       contact_number: '',
    //       education: '',
    //       college: '',
    //       other_college: '',
    //       occupation: '',
    //       annual_income: '',
    //       maritial_status: '',
    //       no_of_children: '',
    //       mother_tongue: '',
    //       denomination: '',
    //       sub_castle: '',
    //       father_status: '',
    //       mother_status: '',
    //       no_of_brothers: '',
    //       no_of_sisters: '',
    //       religious_value: '',
    //       family_income: '',
    //       family_type: '',
    //       family_values: '',
    //       diet: '',
    //       drink: '',
    //       hobbies: '',
    //       languages_known: '',
    //       smoke: '',
    //     )
    // },
    // );
  }
}
